name: sign_in_it_io
description: Flutter package for Google Sign-In built in dart and support both Mobile and Desktop environments.
version: 0.1.0
# homepage: https://github.com/usalko/sign_in_it_io
# commit: 89794a635a5efad6705e3d7ccc29e8139318d947


environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.4
  google_sign_in_platform_interface: ^2.0.1
  shared_preferences: ^2.0.6
  shared_preferences_macos: ^2.0.0
  shared_preferences_linux: ^2.0.0
  url_launcher: ^6.0.6
  url_launcher_macos: ^2.0.0
  meta: ^1.3.0
  crypto: ^3.0.1
  http: ^0.13.0
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter